name: manual-build
on:
  workflow_dispatch:
    inputs:
      imageName:
        description: Full image name (like kartoza/geonode)
        required: true
        default: kartoza/geonode
      imageTag:
        description: Image tag
        required: true
        default: base-latest
      baseImage:
        description: Base GeoNode image to use
        required: true
        default: geonode/spcgeonode:django-3.0
      baseGeoNodeRepo:
        description: Base GeoNode repositories to use
        required: true
        default: https://github.com/kartoza/geonode.git
      baseGeoNodeRepoName:
        description: Git repo name to refer to GeoNode repo
        required: true
        default: kartoza
      baseGeoNodeCommit:
        description: Commit signature of the base code to use
        required: true
jobs:
  docker-builder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ github.event.inputs.imageName }}:${{ github.event.inputs.imageTag }}
          build-args: |
            BASE_IMAGE=${{ github.event.inputs.baseImage }}
            BASE_GEONODE_REPO=${{ github.event.inputs.baseGeoNodeRepo }}
            BASE_GEONODE_REPO_NAME=${{ github.event.inputs.baseGeoNodeRepoName }}
            BASE_GEONODE_COMMIT=${{ github.event.inputs.baseGeoNodeCommit }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
